services:
  app:
    image: ghcr.io/salimkhr/cours-iut-web:staging
    pull_policy: always
    environment:
      - NODE_ENV=staging
      - PORT=3000
    env_file:
      - .env
    restart: unless-stopped
